Controllers/ActorsController.cs
using e_Tickets.Models;
using e_Tickets.Repository;
using Microsoft.AspNetCore.Mvc;

namespace e_Tickets.Controllers
{
    public class ActorsController : Controller
    {
        private readonly IGenericRepository<Actor> context;

        public ActorsController(IGenericRepository<Actor> _context)
        {
            context = _context;
        }
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var data = await context.Getall();
            return View(data);
        }

        #region Create New Actor Action
        [HttpGet]
        public IActionResult Create()
        {
            return View(new Actor());
        }
        [HttpPost]
        public async Task<IActionResult> Create(Actor actor)
        {
            if (ModelState.IsValid)
            {
                await context.Add(actor);
                return RedirectToAction("Index");
            }
            else
            {
                return View();
            }
        }
        #endregion

        #region Update Current Actor Action
        [HttpGet]
        public async Task<IActionResult> Update(int id)
        {
            var found = await context.GetById(id);
            if (found is not null)
            {
                return View(found);
            }
            return RedirectToAction("Index");
        }
        [HttpPost]
        public async Task<IActionResult> Update(int id, Actor actor)
        {
            if (ModelState.IsValid)
            {
                await context.Update(id, actor);
                return RedirectToAction("Index");
            }
            else
            {
                return View(actor);
            }
        }
        #endregion

        #region Delete Actor Action
        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var found = context.GetById(id);
            if (found != null)
            {
                await context.Delete(id);
                return RedirectToAction("Index");
            }
            else
            {
                return RedirectToAction("Index");
            }
        } 
        #endregion
    }
}

Controllers/CinemasController.cs
using e_Tickets.Models;
using e_Tickets.Repository;
using Microsoft.AspNetCore.Mvc;

namespace e_Tickets.Controllers
{
    public class CinemasController : Controller
    {
        private readonly IGenericRepository<Cinema> context;
            
        public CinemasController(IGenericRepository<Cinema> _context)
        {
            context = _context;
        }
        public async Task<IActionResult> Index()
        {
            var cinemas = await context.Getall();
            return View(cinemas);
        }
        #region Create New Cinema Action
        [HttpGet]
        public IActionResult Create()
        {
            return View(new Cinema());
        }
        [HttpPost]
        public async Task<IActionResult> Create(Cinema cinema)
        {
            if (ModelState.IsValid)
            {
                await context.Add(cinema);
                return RedirectToAction("Index");
            }
            else
            {
                return View(cinema);
            }
        }
        #endregion

        #region Update Current Cinema Action
        [HttpGet]
        public async Task<IActionResult> Update(int id)
        {
            var found = await context.GetById(id);
            if (found is not null)
            {
                return View(found);
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Update(int id, Cinema cinema)
        {
            if (ModelState.IsValid)
            {
                await context.Update(id, cinema);
                return RedirectToAction("index");
            }
            else
            {
                return View(cinema);
            }
        }
        #endregion

        #region Delate Cinema Action
        public async Task<IActionResult> Delete(int id)
        {
            var found = await context.GetById(id);
            if (found != null)
            {
                await context.Delete(id);
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        } 
        #endregion
    }
}

Controllers/MoviesController.cs
using e_Tickets.Data.Enum;
using e_Tickets.Models;
using e_Tickets.Repository;
using e_Tickets.Specification;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;

namespace e_Tickets.Controllers
{
    public class MoviesController : Controller
    {
        private readonly IGenericRepository<Movies> context;
        private readonly IGenericRepository<Actor> actorRepository;
        private readonly IGenericRepository<Cinema> cinemaRepository;
        private readonly IGenericRepository<Producer> producerRepository;

        public MoviesController(IGenericRepository<Movies> _context,IGenericRepository<Actor> actorRepository, IGenericRepository<Cinema> cinemaRepository, IGenericRepository<Producer> producerRepository)
        {
            context = _context;
            this.actorRepository = actorRepository;
            this.cinemaRepository = cinemaRepository;
            this.producerRepository = producerRepository;
        }
        public async Task<IActionResult> Index()
        {
            //using specification to get movies with the cinema
            var spec = new MoviesWithCinema();
            var movies = await context.GetAllWithSpec(spec);
            return View(movies);
        }
        #region create new movie action
      
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            ViewBag.Cinemas = await cinemaRepository.Getall();
            ViewBag.Producers = await producerRepository.Getall();
            ViewBag.Categories = Enum.GetValues(typeof(MovieCategory)).Cast<MovieCategory>();
            return View(new Movies());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Movies movie)
        {
            if (ModelState.IsValid)
            {
                await context.Add(movie);
                return RedirectToAction(nameof(Index)); // Redirect to movie list view
            }

            // If model state is not valid, reload the view with the model
            ViewBag.Cinemas = await cinemaRepository.Getall();
            ViewBag.Producers = await producerRepository.Getall();
            ViewBag.Categories = Enum.GetValues(typeof(MovieCategory)).Cast<MovieCategory>();
            return View(movie);
        }
        #endregion

        #region Update current movie Action
        [HttpGet]
        public async Task<IActionResult> Update(int id)
        {
            var found = await context.GetById(id);
            ViewBag.Cinemas = await cinemaRepository.Getall();
            ViewBag.Producers = await producerRepository.Getall();
            ViewBag.Categories = Enum.GetValues(typeof(MovieCategory)).Cast<MovieCategory>();
            return View(found);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(int id, Movies movie)
        {
            if (ModelState.IsValid)
            {
                await context.Update(id, movie);
                return RedirectToAction("Index");
            }
            ViewBag.Cinemas = await cinemaRepository.Getall();
            ViewBag.Producers = await producerRepository.Getall();
            ViewBag.Categories = Enum.GetValues(typeof(MovieCategory)).Cast<MovieCategory>();
            return View();
        }
        #endregion

        #region View movie detailes Action
        [HttpGet]
        public async Task<IActionResult> ViewDetailes(int id)
        {
            //to include cinema name using specification
            var spec = new MoviesWithCinema(id);
            var found = await context.GetByIdWithSpec(spec);
            return View(found);
        }
        #endregion

        #region search movie Action
        [HttpGet]
        public async Task<IActionResult> SearchMovie(string movieName)
        {

            var spec = new MoviesWithCinema(movieName);
            var movies = await context.GetAllWithSpec(spec);

            return View(movies);

        } 
        #endregion 
    }                                                                                                   
}

Controllers/ProducersController.cs
using e_Tickets.Models;
using e_Tickets.Repository;
using Microsoft.AspNetCore.Mvc;

namespace e_Tickets.Controllers
{
    public class ProducersController : Controller
    {
        private readonly IGenericRepository<Producer> context;

        public ProducersController(IGenericRepository<Producer> _context)
        {
            context = _context;
        }
        public async Task <IActionResult> Index()
        {
            var producers = await context.Getall();
            return View(producers);
        }
        #region Create New Producer Action
        [HttpGet]
        public IActionResult Create()
        {
            return View(new Producer());
        }
        [HttpPost]
        public async Task<IActionResult> Create(Producer producer)
        {
            if (ModelState.IsValid)
            {
                await context.Add(producer);
                return RedirectToAction("Index");
            }
            else
            {
                return View(producer);
            }
        } 
        #endregion

        #region Update Current Producer Action
        [HttpGet]
        public async Task<IActionResult> Update(int id)
        {
            var found = await context.GetById(id);
            if (found is not null)
            {
                return View(found);
            }
            else
            {
                return RedirectToAction("Index");
            }
        }
        [HttpPost]
        public async Task<IActionResult> Update(int id, Producer producer)
        {
            if (ModelState.IsValid)
            {
                await context.Update(id, producer);
                return RedirectToAction("Index");
            }
            else
            {
                return View(producer);
            }
        } 
        #endregion

        #region Delete Prducer Action
        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var found = await context.GetById(id);
            if (found != null)
            {
                await context.Delete(id);
                return RedirectToAction("Index");
            }
            else
            {
                return RedirectToAction("Index");
            }
        } 
        #endregion

    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - e_Tickets</title>
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/e_Tickets.styles.css" asp-append-version="true"/>
    @await RenderSectionAsync("Styles", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3 fixed-top">
            <div class="container-md">
                <a class="navbar-brand" asp-area="" asp-controller="Movies" asp-action="Index">E_Tickets</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                           <a class="nav-link text-dark" asp-controller="Movies" asp-action="Index">
                                <i class="fa-solid fa-film"></i> Movies
                           </a>
                       </li>
                       <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                                <i class="fa-solid fa-gear"></i> Managment
                           </a>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                                <a class="dropdown-item" asp-controller="Cinemas" asp-action="Index"><i class="fa-solid fa-video"></i> Cinemas</a>
                                <a class="dropdown-item" asp-controller="Actors" asp-action="Index"><i class="fa-solid fa-users"></i> Actors</a>
                                <a class="dropdown-item" asp-controller="Producers" asp-action="Index"><i class="fa-solid fa-headset"></i> Producers</a>
                           </div>
                       </li>
                    </ul>
                    <form class="d-flex" asp-controller="Movies" asp-action="SearchMovie" method="get">
                        <input class="form-control me-2" type="search" placeholder="Search Movies.." aria-label="Search" name="movieName">
                        <button class ="btn btn-outline-info movieSearch" type="submit">Search</button>
                    </form>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-md">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="text-center text-white" style="background-color: #f1f1f1;">
        <!-- Grid container -->
        <div class="container pt-4">
            <!-- Section: Social media -->
            <section class="mb-4">
                <!-- Facebook -->
                <a class="btn btn-link btn-floating btn-lg text-dark m-1"
                    href="#!"
                    role="button"
                    data-mdb-ripple-color="dark">
                    <i class="fab fa-facebook-f"></i>
                </a>

                <!-- Twitter -->
                <a class="btn btn-link btn-floating btn-lg text-dark m-1"
                    href="#!"
                    role="button"
                    data-mdb-ripple-color="dark">
                    <i class="fab fa-twitter"></i>
                </a>

                <!-- Google -->
                <a class="btn btn-link btn-floating btn-lg text-dark m-1"
                    href="#!"
                    role="button"
                    data-mdb-ripple-color="dark">
                    <i class="fab fa-google"></i>
                </a>

                <!-- Instagram -->
                <a class="btn btn-link btn-floating btn-lg text-dark m-1"
                    href="#!"
                    role="button"
                    data-mdb-ripple-color="dark">
                    <i class="fab fa-instagram"></i>
                </a>

                <!-- Linkedin -->
                <a class="btn btn-link btn-floating btn-lg text-dark m-1"
                    href="#!"
                    role="button"
                    data-mdb-ripple-color="dark">
                    <i class="fab fa-linkedin"></i>
                </a>
                <!-- Github -->
                <a class="btn btn-link btn-floating btn-lg text-dark m-1"
                    href="#!"
                    role="button"
                    data-mdb-ripple-color="dark">
                    <i class="fab fa-github"></i>
                </a>
            </section>
            <!-- Section: Social media -->
        </div>
        <!-- Grid container -->
        <!-- Copyright -->
        <div class="text-center text-dark p-3" style="background-color: rgba(0, 0, 0, 0.2);">
            © 2023 Copyright:
            <a class="text-dark" href="#">Mo3tef.com</a>
        </div>
        <!-- Copyright -->
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
   
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>